import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import Link from "next/link";
import CartButton from "./cart/CartButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-between items-center mb-6 p-4">
          <h1 className="text-2xl font-bold">My Shop</h1>
          <CartButton />
        </div>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
